apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
    type: backend

spec:
  template:
    metadata:
      name: auth-pod
      labels:
        app: auth
        type: backend
    spec:
      containers:
        - name: authsrv
          image: singaravelan21/todo_list_auth_srv:v1.0.6
  replicas: 3
  selector:
    matchLabels:
      app: auth

---

apiVersion: v1
kind: Service
metadata:
  name: todolistauthsrv
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - targetPort: 8083
      port: 8083